// Failure-path E2E coverage. No API routes are mocked: Chromium, axum, SQLite,
// filesystem, and the loopback provider are all real.
const { chromium } = require('playwright');
const http = require('http');
const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const assert = require('assert');
const { spawn, execFileSync } = require('child_process');
const root = path.resolve(__dirname, '..');
const binary = path.join(root, 'target', 'debug', 'harness');
const token = () => 'e2e-failure-' + crypto.randomBytes(24).toString('hex');
const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
async function waitFor(fn, timeout = 30000, label = 'condition') { const end = Date.now() + timeout; while (Date.now() < end) { try { const value = await fn(); if (value) return value; } catch {} await wait(150); } throw new Error(`Timed out waiting for ${label}`); }
function json(res, status, body) { const b = Buffer.from(JSON.stringify(body)); res.writeHead(status, { 'content-type': 'application/json', 'content-length': b.length }); res.end(b); }
function providerServer(mode) {
  const calls = [];
  const server = http.createServer((req, res) => {
    if (req.method === 'GET' && req.url === '/v1/models') return json(res, 200, { data: [{ id: 'e2e-model' }] });
    if (req.method !== 'POST' || req.url !== '/v1/chat/completions') return json(res, 404, { error: 'not found' });
    let raw = ''; req.on('data', chunk => { raw += chunk; }); req.on('end', () => {
      const body = JSON.parse(raw); calls.push(body); const messages = body.messages || []; const tools = messages.filter(m => m.role === 'tool'); let reply;
      if (JSON.stringify(messages).includes('HARNESS_VERIFICATION_V1')) reply = { role: 'assistant', content: JSON.stringify({ claims: [], skipped_diagnostics: [] }) };
      else if (!tools.length) reply = { role: 'assistant', content: null, tool_calls: [{ id: 'read-1', type: 'function', function: { name: 'read', arguments: JSON.stringify({ path: 'notes.md' }) } }] };
      else if (!tools.some(m => m.tool_call_id === 'edit-1')) reply = { role: 'assistant', content: null, tool_calls: [{ id: 'edit-1', type: 'function', function: { name: 'edit', arguments: JSON.stringify({ path: 'notes.md', anchors: [{ line: 2, hash: 'f44e' }], old_string: 'beta', new_string: 'gamma' }) } }] };
      else if (mode === 'crash' && !tools.some(m => m.tool_call_id === 'bash-1')) reply = { role: 'assistant', content: null, tool_calls: [{ id: 'bash-1', type: 'function', function: { name: 'bash', arguments: JSON.stringify({ command: "printf 'verified\\n'", description: 'Verify the edit' }) } }] };
      else reply = { role: 'assistant', content: mode === 'deny' ? 'The edit was denied and the file was left unchanged.' : 'Changed beta to gamma and verified it.' };
      json(res, 200, { choices: [{ message: reply }], usage: { prompt_tokens: 11, completion_tokens: 7 } });
    });
  });
  return new Promise(resolve => server.listen(0, '127.0.0.1', () => resolve({ server, calls, port: server.address().port })));
}
function launch(env) { const child = spawn(binary, [], { cwd: root, env: { ...process.env, ...env }, stdio: ['ignore', 'pipe', 'pipe'] }); let out = '', err = ''; child.stdout.on('data', x => { out += x; }); child.stderr.on('data', x => { err += x; }); child.diag = () => `stdout:\n${out}\nstderr:\n${err}`; return child; }
async function stop(child, signal = 'SIGTERM') { if (!child || child.exitCode !== null) return; child.kill(signal); await Promise.race([new Promise(resolve => child.once('exit', resolve)), wait(3000).then(() => child.kill('SIGKILL'))]); }
function sql(db, statement) { return JSON.parse(execFileSync('python3', ['-c', 'import json,sqlite3,sys; c=sqlite3.connect(sys.argv[1]); c.row_factory=sqlite3.Row; print(json.dumps([dict(r) for r in c.execute(sys.argv[2])]))', db, statement]).toString()); }
async function incident(port, auth, requestId) { const response = await fetch(`http://127.0.0.1:${port}/chat/requests/${requestId}/incident`, { headers: { Authorization: `Bearer ${auth}` } }); assert.strictEqual(response.status, 200); return response.json(); }
async function boot(project, db, auth, provider) { const port = await new Promise(resolve => { const s = http.createServer().listen(0, '127.0.0.1', function () { const p = this.address().port; this.close(() => resolve(p)); }); }); const app = launch({ HARNESS_ADDR: `127.0.0.1:${port}`, HARNESS_DB: db, HARNESS_AUTH_TOKEN: auth, HARNESS_API_KEY: 'e2e-provider-key', HARNESS_BASE_URL: `http://127.0.0.1:${provider.port}/v1`, HARNESS_MODEL: 'e2e-model' }); await waitFor(async () => { try { return (await fetch(`http://127.0.0.1:${port}/memory/status`, { headers: { Authorization: `Bearer ${auth}` } })).ok; } catch { return false; } }, 30000, 'Rust readiness'); return { app, port }; }
async function configure(page, project) { await page.click('[data-view="settings"]'); await page.waitForTimeout(300); await page.fill('#rootpath', project); await page.selectOption('#permissionmode', 'ask'); await page.fill('#diagnosticscmd', 'grep -q gamma notes.md'); await page.click('#projectform button[type="submit"]'); await waitFor( async () => (await page.locator('#notice').innerText()).includes('saved'), 10000, 'scope save'); await page.click('[data-view="chat"]'); await waitFor(() => page.locator('#setup-banner').evaluate(el => el.hidden), 10000, 'scope ready'); }
async function denial() {
  const auth = token(), fixture = fs.mkdtempSync(path.join(os.tmpdir(), 'harness-deny-')), dbDir = fs.mkdtempSync(path.join(os.tmpdir(), 'harness-deny-db-')), project = path.join(fixture, 'project'), db = path.join(dbDir, 'harness.db'); fs.mkdirSync(project); fs.writeFileSync(path.join(project, 'notes.md'), 'alpha\nbeta\n'); const provider = await providerServer('deny'); let browser, app, appPort;
  try { ({ app, port: appPort } = await boot(project, db, auth, provider)); browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH || chromium.executablePath(), args: ['--no-sandbox'] }); const page = await browser.newPage(); await page.goto(`http://127.0.0.1:${appPort}/`); await page.fill('#token', auth); await page.click('#authform button'); await page.waitForFunction(() => !document.querySelector('#workspace').hidden); await configure(page, project); await page.fill('#prompt', 'Change beta to gamma in notes.md'); await page.click('#send'); await page.waitForSelector('#agent-permission:not([hidden])', { timeout: 45000 }); assert((await page.locator('#permission-summary').innerText()).includes('edit notes.md')); await page.click('#permission-deny'); await waitFor(() => page.locator('#notice').innerText().then(t => t.includes('Answer saved')), 45000, 'denial answer'); assert((await page.locator('#log').innerText()).includes('denied')); assert.strictEqual(fs.readFileSync(path.join(project, 'notes.md'), 'utf8'), 'alpha\nbeta\n'); const permissions = sql(db, 'SELECT request_id,tool_name,status FROM permission_requests'); const steps = sql(db, 'SELECT tool_name,status,error_code FROM turn_steps WHERE tool_name IS NOT NULL ORDER BY seq'); assert(permissions.some(x => x.tool_name === 'edit' && x.status === 'denied'), JSON.stringify(permissions)); assert(steps.some(x => x.tool_name === 'edit' && x.status === 'denied'), JSON.stringify(steps)); const graph = await incident(appPort, auth, permissions[0].request_id); assert(graph.edges.some(edge => edge.relation === 'triggers' && edge.source.startsWith('permission:') && edge.target.startsWith('step:')), JSON.stringify(graph)); assert.strictEqual(graph.edges.some(edge => edge.relation === 'authorizes'), false); assert(provider.calls.some(x => JSON.stringify(x).includes('denied')), 'provider did not receive the denial result'); console.log('DENIAL E2E passed: approval denied, file unchanged, causal denial persisted and returned to provider'); }
  finally { await browser?.close(); await stop(app); await new Promise(resolve => provider.server.close(resolve)); fs.rmSync(fixture, { recursive: true, force: true }); fs.rmSync(dbDir, { recursive: true, force: true }); }
}
async function crashRecovery() {
  const auth = token(), fixture = fs.mkdtempSync(path.join(os.tmpdir(), 'harness-crash-')), dbDir = fs.mkdtempSync(path.join(os.tmpdir(), 'harness-crash-db-')), project = path.join(fixture, 'project'), db = path.join(dbDir, 'harness.db'); fs.mkdirSync(project); fs.writeFileSync(path.join(project, 'notes.md'), 'alpha\nbeta\n'); const provider = await providerServer('crash'); let browser, app, appPort;
  try { ({ app, port: appPort } = await boot(project, db, auth, provider)); browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH || chromium.executablePath(), args: ['--no-sandbox'] }); const page = await browser.newPage(); await page.goto(`http://127.0.0.1:${appPort}/`); await page.fill('#token', auth); await page.click('#authform button'); await page.waitForFunction(() => !document.querySelector('#workspace').hidden); await configure(page, project); await page.fill('#prompt', 'Change beta to gamma in notes.md, then verify it'); await page.click('#send'); await page.waitForSelector('#agent-permission:not([hidden])', { timeout: 45000 }); await page.click('#permission-approve'); await page.waitForFunction(() => document.querySelector('#permission-summary')?.textContent.includes('bash'), null, { timeout: 45000 }); await stop(app, 'SIGKILL'); app = null; assert.strictEqual(fs.readFileSync(path.join(project, 'notes.md'), 'utf8'), 'alpha\ngamma\n'); const resumed = await boot(project, db, auth, provider); app = resumed.app; appPort = resumed.port; const rows = sql(db, 'SELECT id,status,tool_name,error_code FROM turn_steps ORDER BY seq'); const receipt = sql(db, 'SELECT request_id,state,error_code FROM chat_receipts ORDER BY updated_at DESC LIMIT 1'); const changes = sql(db, 'SELECT path,applied FROM file_changes'); const interrupted = rows.find(x => x.status === 'interrupted'); assert(interrupted, JSON.stringify(rows)); assert.strictEqual(interrupted.tool_name, 'bash'); assert.strictEqual(rows.some(x => x.status === 'running'), false); assert.strictEqual(receipt[0].state, 'interrupted'); assert.strictEqual(receipt[0].error_code, 'process_restarted'); assert.strictEqual(changes.filter(x => x.path === 'notes.md').length, 1); assert.strictEqual(rows.filter(x => x.tool_name === 'edit').length, 1); assert.strictEqual(rows.filter(x => x.tool_name === 'bash').length, 1); const graph = await incident(appPort, auth, receipt[0].request_id); const recovery = graph.edges.find(edge => edge.relation === 'triggers' && edge.target.startsWith('recovery:')); assert(recovery, JSON.stringify(graph)); assert.strictEqual(recovery.source, 'step:' + interrupted.id); assert.strictEqual(graph.earliest_known_break.node_id, 'step:' + interrupted.id); await stop(app); app = null; console.log('CRASH-RECOVERY E2E passed: restart linked the exact interrupted bash step and replayed no side effect'); }
  finally { await browser?.close(); await stop(app); await new Promise(resolve => provider.server.close(resolve)); fs.rmSync(fixture, { recursive: true, force: true }); fs.rmSync(dbDir, { recursive: true, force: true }); }
}
(async () => { assert(fs.existsSync(binary), `missing ${binary}; run cargo build --locked first`); await denial(); await crashRecovery(); console.log('Failure-path E2E passed: denial + crash recovery'); })().catch(error => { console.error(error.stack || error); process.exit(1); });
